/* Generated by: /Users/sfegan/GitHub/fftw3/genfft/gen_r2cf.native -n 60 -standalone -fma -generic-arith -compact -name dft_codelet_r2cf_60 */

/*
 * This function contains 374 FP additions, 154 FP multiplications,
 * (or, 234 additions, 14 multiplications, 140 fused multiply/add),
 * 101 stack variables, 8 constants, and 120 memory accesses
 */
void dft_codelet_r2cf_60(R * R0, R * R1, R * Cr, R * Ci, stride rs, stride csr, stride csi, INT v, INT ivs, INT ovs)
{
  DK(KP951056516, +0.951056516295153572116439333379382143405698634);
  DK(KP823639103, +0.823639103546331925877420039278190003029660514);
  DK(KP910592997, +0.910592997310029334643087372129977886038870291);
  DK(KP866025403, +0.866025403784438646763723170752936183471402627);
  DK(KP500000000, +0.500000000000000000000000000000000000000000000);
  DK(KP559016994, +0.559016994374947424102293417182819058860154590);
  DK(KP250000000, +0.250000000000000000000000000000000000000000000);
  DK(KP618033988, +0.618033988749894848204586834365638117720309180);
  {
    INT i;
    for (i = v; i > 0; i = i - 1, R0 = R0 + ivs, R1 = R1 + ivs, Cr = Cr + ovs, Ci = Ci + ovs, MAKE_VOLATILE_STRIDE(240, rs), MAKE_VOLATILE_STRIDE(240, csr), MAKE_VOLATILE_STRIDE(240, csi)) {
      E T9, T2P, T28, TZ, T2t, T1q, T5G, T2J, T4g, T5c, T1N, T5B, T2E,
       T45, T5h;
      E TC, T2U, T2j, T1a, T2y, Ti, Tr, T12, T2u, T2S, T4U, T2f, T3I,
       T15, T2v;
      E T5H, T5I, T1F, T4j, T3m, T4K, T3f, T4J, T2M, T5f, T5C, T5D,
       T22, T48, T3D;
      E T4O, T3w, T4P, T2H, T5k, TL, TU, T1d, T2z, T2X, T4X, T2q, T3L,
       T1g, T2A;
      {
        E T1, T4, T7, T8, T27, T26, TX, TY;
        T1 = R0[0];
        {
          E T2, T3, T5, T6;
          T2 = R0[WS(rs, 6)];
          T3 = R0[WS(rs, 24)];
          T4 = ADD(T2, T3);
          T5 = R0[WS(rs, 12)];
          T6 = R0[WS(rs, 18)];
          T7 = ADD(T5, T6);
          T8 = ADD(T4, T7);
          T27 = SUB(T5, T6);
          T26 = SUB(T2, T3);
        }
        T9 = ADD(T1, T8);
        T2P = FNMS(KP618033988, T26, T27);
        T28 = FMA(KP618033988, T27, T26);
        TX = FNMS(KP250000000, T8, T1);
        TY = SUB(T4, T7);
        TZ = FMA(KP559016994, TY, TX);
        T2t = FNMS(KP559016994, TY, TX);
      }
      {
        E T4a, T4b, T4c, T1m, T4d, T1p, T4e, T4f;
        T4a = R1[WS(rs, 7)];
        {
          E T1k, T1l, T1n, T1o;
          T1k = R1[WS(rs, 13)];
          T1l = R1[WS(rs, 1)];
          T4b = ADD(T1k, T1l);
          T1n = R1[WS(rs, 19)];
          T1o = R1[WS(rs, 25)];
          T4c = ADD(T1n, T1o);
          T1m = SUB(T1k, T1l);
          T4d = ADD(T4b, T4c);
          T1p = SUB(T1n, T1o);
        }
        T1q = FMA(KP618033988, T1p, T1m);
        T5G = ADD(T4a, T4d);
        T2J = FNMS(KP618033988, T1m, T1p);
        T4e = FNMS(KP250000000, T4d, T4a);
        T4f = SUB(T4b, T4c);
        T4g = FMA(KP559016994, T4f, T4e);
        T5c = FNMS(KP559016994, T4f, T4e);
      }
      {
        E T3Z, T40, T41, T1J, T42, T1M, T43, T44;
        T3Z = R1[WS(rs, 22)];
        {
          E T1H, T1I, T1K, T1L;
          T1H = R1[WS(rs, 28)];
          T1I = R1[WS(rs, 16)];
          T40 = ADD(T1H, T1I);
          T1K = R1[WS(rs, 4)];
          T1L = R1[WS(rs, 10)];
          T41 = ADD(T1K, T1L);
          T1J = SUB(T1H, T1I);
          T42 = ADD(T40, T41);
          T1M = SUB(T1K, T1L);
        }
        T1N = FMA(KP618033988, T1M, T1J);
        T5B = ADD(T3Z, T42);
        T2E = FNMS(KP618033988, T1J, T1M);
        T43 = FNMS(KP250000000, T42, T3Z);
        T44 = SUB(T40, T41);
        T45 = FMA(KP559016994, T44, T43);
        T5h = FNMS(KP559016994, T44, T43);
      }
      {
        E Tu, Tx, TA, TB, T2i, T2h, T18, T19;
        Tu = R0[WS(rs, 15)];
        {
          E Tv, Tw, Ty, Tz;
          Tv = R0[WS(rs, 21)];
          Tw = R0[WS(rs, 9)];
          Tx = ADD(Tv, Tw);
          Ty = R0[WS(rs, 27)];
          Tz = R0[WS(rs, 3)];
          TA = ADD(Ty, Tz);
          TB = ADD(Tx, TA);
          T2i = SUB(Ty, Tz);
          T2h = SUB(Tv, Tw);
        }
        TC = ADD(Tu, TB);
        T2U = FNMS(KP618033988, T2h, T2i);
        T2j = FMA(KP618033988, T2i, T2h);
        T18 = FNMS(KP250000000, TB, Tu);
        T19 = SUB(Tx, TA);
        T1a = FMA(KP559016994, T19, T18);
        T2y = FNMS(KP559016994, T19, T18);
      }
      {
        E Ta, Tj, Td, Tg, Th, T2a, T29, Tm, Tp, Tq, T2d, T2c;
        Ta = R0[WS(rs, 10)];
        Tj = R0[WS(rs, 20)];
        {
          E Tb, Tc, Te, Tf;
          Tb = R0[WS(rs, 16)];
          Tc = R0[WS(rs, 4)];
          Td = ADD(Tb, Tc);
          Te = R0[WS(rs, 22)];
          Tf = R0[WS(rs, 28)];
          Tg = ADD(Te, Tf);
          Th = ADD(Td, Tg);
          T2a = SUB(Te, Tf);
          T29 = SUB(Tb, Tc);
        }
        {
          E Tk, Tl, Tn, To;
          Tk = R0[WS(rs, 26)];
          Tl = R0[WS(rs, 14)];
          Tm = ADD(Tk, Tl);
          Tn = R0[WS(rs, 2)];
          To = R0[WS(rs, 8)];
          Tp = ADD(Tn, To);
          Tq = ADD(Tm, Tp);
          T2d = SUB(Tn, To);
          T2c = SUB(Tk, Tl);
        }
        {
          E T10, T11, T2Q, T2R;
          Ti = ADD(Ta, Th);
          Tr = ADD(Tj, Tq);
          T10 = FNMS(KP250000000, Th, Ta);
          T11 = SUB(Td, Tg);
          T12 = FMA(KP559016994, T11, T10);
          T2u = FNMS(KP559016994, T11, T10);
          T2Q = FNMS(KP618033988, T29, T2a);
          T2R = FNMS(KP618033988, T2c, T2d);
          T2S = ADD(T2Q, T2R);
          T4U = SUB(T2Q, T2R);
          {
            E T2b, T2e, T13, T14;
            T2b = FMA(KP618033988, T2a, T29);
            T2e = FMA(KP618033988, T2d, T2c);
            T2f = ADD(T2b, T2e);
            T3I = SUB(T2e, T2b);
            T13 = FNMS(KP250000000, Tq, Tj);
            T14 = SUB(Tm, Tp);
            T15 = FMA(KP559016994, T14, T13);
            T2v = FNMS(KP559016994, T14, T13);
          }
        }
      }
      {
        E T39, T3g, T3h, T3i, T1t, T3j, T1w, T3a, T3b, T1A, T3c, T1D;
        T39 = R1[WS(rs, 27)];
        T3g = R1[WS(rs, 17)];
        {
          E T1r, T1s, T1u, T1v;
          T1r = R1[WS(rs, 23)];
          T1s = R1[WS(rs, 11)];
          T3h = ADD(T1r, T1s);
          T1u = R1[WS(rs, 29)];
          T1v = R1[WS(rs, 5)];
          T3i = ADD(T1u, T1v);
          T1t = SUB(T1r, T1s);
          T3j = ADD(T3h, T3i);
          T1w = SUB(T1u, T1v);
        }
        {
          E T1y, T1z, T1B, T1C;
          T1y = R1[WS(rs, 3)];
          T1z = R1[WS(rs, 21)];
          T3a = ADD(T1y, T1z);
          T1B = R1[WS(rs, 9)];
          T1C = R1[WS(rs, 15)];
          T3b = ADD(T1B, T1C);
          T1A = SUB(T1y, T1z);
          T3c = ADD(T3a, T3b);
          T1D = SUB(T1B, T1C);
        }
        {
          E T1x, T1E, T3k, T3l;
          T5H = ADD(T3g, T3j);
          T5I = ADD(T39, T3c);
          T1x = FMA(KP618033988, T1w, T1t);
          T1E = FMA(KP618033988, T1D, T1A);
          T1F = ADD(T1x, T1E);
          T4j = SUB(T1E, T1x);
          T3k = FNMS(KP250000000, T3j, T3g);
          T3l = SUB(T3h, T3i);
          T3m = FMA(KP559016994, T3l, T3k);
          T4K = FNMS(KP559016994, T3l, T3k);
          {
            E T3d, T3e, T2K, T2L;
            T3d = FNMS(KP250000000, T3c, T39);
            T3e = SUB(T3a, T3b);
            T3f = FMA(KP559016994, T3e, T3d);
            T4J = FNMS(KP559016994, T3e, T3d);
            T2K = FNMS(KP618033988, T1t, T1w);
            T2L = FNMS(KP618033988, T1A, T1D);
            T2M = ADD(T2K, T2L);
            T5f = SUB(T2K, T2L);
          }
        }
      }
      {
        E T3q, T3x, T3y, T3z, T1Q, T3A, T1T, T3r, T3s, T1X, T3t, T20;
        T3q = R1[WS(rs, 12)];
        T3x = R1[WS(rs, 2)];
        {
          E T1O, T1P, T1R, T1S;
          T1O = R1[WS(rs, 8)];
          T1P = R1[WS(rs, 26)];
          T3y = ADD(T1O, T1P);
          T1R = R1[WS(rs, 14)];
          T1S = R1[WS(rs, 20)];
          T3z = ADD(T1R, T1S);
          T1Q = SUB(T1O, T1P);
          T3A = ADD(T3y, T3z);
          T1T = SUB(T1R, T1S);
        }
        {
          E T1V, T1W, T1Y, T1Z;
          T1V = R1[WS(rs, 18)];
          T1W = R1[WS(rs, 6)];
          T3r = ADD(T1V, T1W);
          T1Y = R1[WS(rs, 24)];
          T1Z = R1[0];
          T3s = ADD(T1Y, T1Z);
          T1X = SUB(T1V, T1W);
          T3t = ADD(T3r, T3s);
          T20 = SUB(T1Y, T1Z);
        }
        {
          E T1U, T21, T3B, T3C;
          T5C = ADD(T3x, T3A);
          T5D = ADD(T3q, T3t);
          T1U = FMA(KP618033988, T1T, T1Q);
          T21 = FMA(KP618033988, T20, T1X);
          T22 = ADD(T1U, T21);
          T48 = SUB(T21, T1U);
          T3B = FNMS(KP250000000, T3A, T3x);
          T3C = SUB(T3y, T3z);
          T3D = FMA(KP559016994, T3C, T3B);
          T4O = FNMS(KP559016994, T3C, T3B);
          {
            E T3u, T3v, T2F, T2G;
            T3u = FNMS(KP250000000, T3t, T3q);
            T3v = SUB(T3r, T3s);
            T3w = FMA(KP559016994, T3v, T3u);
            T4P = FNMS(KP559016994, T3v, T3u);
            T2F = FNMS(KP618033988, T1Q, T1T);
            T2G = FNMS(KP618033988, T1X, T20);
            T2H = ADD(T2F, T2G);
            T5k = SUB(T2F, T2G);
          }
        }
      }
      {
        E TD, TM, TG, TJ, TK, T2l, T2k, TP, TS, TT, T2o, T2n;
        TD = R0[WS(rs, 25)];
        TM = R0[WS(rs, 5)];
        {
          E TE, TF, TH, TI;
          TE = R0[WS(rs, 1)];
          TF = R0[WS(rs, 19)];
          TG = ADD(TE, TF);
          TH = R0[WS(rs, 7)];
          TI = R0[WS(rs, 13)];
          TJ = ADD(TH, TI);
          TK = ADD(TG, TJ);
          T2l = SUB(TH, TI);
          T2k = SUB(TE, TF);
        }
        {
          E TN, TO, TQ, TR;
          TN = R0[WS(rs, 11)];
          TO = R0[WS(rs, 29)];
          TP = ADD(TN, TO);
          TQ = R0[WS(rs, 17)];
          TR = R0[WS(rs, 23)];
          TS = ADD(TQ, TR);
          TT = ADD(TP, TS);
          T2o = SUB(TQ, TR);
          T2n = SUB(TN, TO);
        }
        {
          E T1b, T1c, T2V, T2W;
          TL = ADD(TD, TK);
          TU = ADD(TM, TT);
          T1b = FNMS(KP250000000, TK, TD);
          T1c = SUB(TG, TJ);
          T1d = FMA(KP559016994, T1c, T1b);
          T2z = FNMS(KP559016994, T1c, T1b);
          T2V = FNMS(KP618033988, T2k, T2l);
          T2W = FNMS(KP618033988, T2n, T2o);
          T2X = ADD(T2V, T2W);
          T4X = SUB(T2V, T2W);
          {
            E T2m, T2p, T1e, T1f;
            T2m = FMA(KP618033988, T2l, T2k);
            T2p = FMA(KP618033988, T2o, T2n);
            T2q = ADD(T2m, T2p);
            T3L = SUB(T2p, T2m);
            T1e = FNMS(KP250000000, TT, TM);
            T1f = SUB(TP, TS);
            T1g = FMA(KP559016994, T1f, T1e);
            T2A = FNMS(KP559016994, T1f, T1e);
          }
        }
      }
      {
        E Tt, T5P, TW, T5Q, T5K, T5T, T5F, T5U, T60, T62, T5O, T5X,
         T5L, T61;
        {
          E Ts, TV, T5J, T5E;
          Ts = ADD(Ti, Tr);
          Tt = ADD(T9, Ts);
          T5P = FNMS(KP500000000, Ts, T9);
          TV = ADD(TL, TU);
          TW = ADD(TC, TV);
          T5Q = FNMS(KP500000000, TV, TC);
          T5J = ADD(T5H, T5I);
          T5K = FNMS(KP500000000, T5J, T5G);
          T5T = ADD(T5G, T5J);
          T5E = ADD(T5C, T5D);
          T5F = FNMS(KP500000000, T5E, T5B);
          T5U = ADD(T5B, T5E);
          {
            E T5Y, T5Z, T5M, T5N;
            T5Y = SUB(T5H, T5I);
            T5Z = SUB(T5D, T5C);
            T60 = SUB(T5Y, T5Z);
            T62 = ADD(T5Y, T5Z);
            T5M = SUB(TU, TL);
            T5N = SUB(Tr, Ti);
            T5O = SUB(T5M, T5N);
            T5X = ADD(T5N, T5M);
          }
        }
        Cr[WS(csr, 15)] = SUB(Tt, TW);
        Ci[WS(csi, 15)] = SUB(T5T, T5U);
        Ci[WS(csi, 10)] = MUL(KP866025403, ADD(T5X, T60));
        Ci[WS(csi, 20)] = MUL(KP866025403, SUB(T60, T5X));
        T5L = SUB(T5F, T5K);
        Ci[WS(csi, 5)] = FMA(KP866025403, T5O, T5L);
        Ci[WS(csi, 25)] = FNMS(KP866025403, T5O, T5L);
        T61 = SUB(T5P, T5Q);
        Cr[WS(csr, 25)] = FNMS(KP866025403, T62, T61);
        Cr[WS(csr, 5)] = FMA(KP866025403, T62, T61);
        {
          E T5R, T5S, T5V, T5W;
          T5R = ADD(T5P, T5Q);
          T5S = ADD(T5K, T5F);
          Cr[WS(csr, 10)] = SUB(T5R, T5S);
          Cr[WS(csr, 20)] = ADD(T5R, T5S);
          T5V = ADD(Tt, TW);
          T5W = ADD(T5T, T5U);
          Cr[WS(csr, 30)] = SUB(T5V, T5W);
          Cr[0] = ADD(T5V, T5W);
        }
      }
      {
        E T2O, T30, T4D, T57, T4R, T55, T2Z, T5y, T4M, T54, T4G, T58,
         T5g, T5v, T5p;
        E T2x, T51, T4V, T5l, T5w, T5q, T2C, T52, T4Y;
        {
          E T4N, T4Q, T2w, T4T;
          {
            E T2I, T2N, T4B, T4C;
            T2I = ADD(T2E, T2H);
            T2N = ADD(T2J, T2M);
            T2O = SUB(T2I, T2N);
            T30 = ADD(T2N, T2I);
            T4B = FNMS(KP500000000, T2S, T2P);
            T4C = SUB(T2v, T2u);
            T4D = FNMS(KP910592997, T4C, T4B);
            T57 = FMA(KP910592997, T4C, T4B);
          }
          T4N = FNMS(KP500000000, T2H, T2E);
          T4Q = SUB(T4O, T4P);
          T4R = FMA(KP910592997, T4Q, T4N);
          T55 = FNMS(KP910592997, T4Q, T4N);
          {
            E T2T, T2Y, T4I, T4L;
            T2T = ADD(T2P, T2S);
            T2Y = ADD(T2U, T2X);
            T2Z = ADD(T2T, T2Y);
            T5y = SUB(T2Y, T2T);
            T4I = FNMS(KP500000000, T2M, T2J);
            T4L = SUB(T4J, T4K);
            T4M = FNMS(KP910592997, T4L, T4I);
            T54 = FMA(KP910592997, T4L, T4I);
          }
          {
            E T4E, T4F, T5d, T5e;
            T4E = FNMS(KP500000000, T2X, T2U);
            T4F = SUB(T2A, T2z);
            T4G = FNMS(KP910592997, T4F, T4E);
            T58 = FMA(KP910592997, T4F, T4E);
            T5d = ADD(T4K, T4J);
            T5e = FNMS(KP500000000, T5d, T5c);
            T5g = FNMS(KP823639103, T5f, T5e);
            T5v = ADD(T5c, T5d);
            T5p = FMA(KP823639103, T5f, T5e);
          }
          T2w = ADD(T2u, T2v);
          T4T = FNMS(KP500000000, T2w, T2t);
          T2x = ADD(T2t, T2w);
          T51 = FMA(KP823639103, T4U, T4T);
          T4V = FNMS(KP823639103, T4U, T4T);
          {
            E T5i, T5j, T2B, T4W;
            T5i = ADD(T4O, T4P);
            T5j = FNMS(KP500000000, T5i, T5h);
            T5l = FNMS(KP823639103, T5k, T5j);
            T5w = ADD(T5h, T5i);
            T5q = FMA(KP823639103, T5k, T5j);
            T2B = ADD(T2z, T2A);
            T4W = FNMS(KP500000000, T2B, T2y);
            T2C = ADD(T2y, T2B);
            T52 = FMA(KP823639103, T4X, T4W);
            T4Y = FNMS(KP823639103, T4X, T4W);
          }
        }
        {
          E T2D, T5x, T59, T5a;
          Ci[WS(csi, 12)] = MUL(KP951056516, ADD(T2Z, T30));
          Ci[WS(csi, 18)] = MUL(KP951056516, SUB(T30, T2Z));
          T2D = SUB(T2x, T2C);
          Cr[WS(csr, 3)] = FNMS(KP951056516, T2O, T2D);
          Cr[WS(csr, 27)] = FMA(KP951056516, T2O, T2D);
          T5x = SUB(T5v, T5w);
          Ci[WS(csi, 3)] = FMA(KP951056516, T5y, T5x);
          Ci[WS(csi, 27)] = FNMS(KP951056516, T5y, T5x);
          {
            E T5t, T5u, T5z, T5A;
            T5t = ADD(T51, T52);
            T5u = ADD(T5p, T5q);
            Cr[WS(csr, 22)] = SUB(T5t, T5u);
            Cr[WS(csr, 8)] = ADD(T5t, T5u);
            T5z = ADD(T2x, T2C);
            T5A = ADD(T5v, T5w);
            Cr[WS(csr, 18)] = SUB(T5z, T5A);
            Cr[WS(csr, 12)] = ADD(T5z, T5A);
          }
          T59 = ADD(T57, T58);
          T5a = ADD(T54, T55);
          Ci[WS(csi, 8)] = NEG(MUL(KP951056516, ADD(T59, T5a)));
          Ci[WS(csi, 22)] = MUL(KP951056516, SUB(T59, T5a));
          {
            E T5b, T5m, T4H, T4S;
            T5b = ADD(T4V, T4Y);
            T5m = ADD(T5g, T5l);
            Cr[WS(csr, 2)] = SUB(T5b, T5m);
            Cr[WS(csr, 28)] = ADD(T5b, T5m);
            T4H = ADD(T4D, T4G);
            T4S = ADD(T4M, T4R);
            Ci[WS(csi, 2)] = MUL(KP951056516, SUB(T4H, T4S));
            Ci[WS(csi, 28)] = NEG(MUL(KP951056516, ADD(T4H, T4S)));
          }
          {
            E T4Z, T50, T5n, T5o;
            T4Z = SUB(T4V, T4Y);
            T50 = SUB(T4R, T4M);
            Cr[WS(csr, 17)] = FNMS(KP951056516, T50, T4Z);
            Cr[WS(csr, 13)] = FMA(KP951056516, T50, T4Z);
            T5n = SUB(T5l, T5g);
            T5o = SUB(T4G, T4D);
            Ci[WS(csi, 13)] = FMA(KP951056516, T5o, T5n);
            Ci[WS(csi, 17)] = FNMS(KP951056516, T5o, T5n);
          }
          {
            E T53, T56, T5r, T5s;
            T53 = SUB(T51, T52);
            T56 = SUB(T54, T55);
            Cr[WS(csr, 7)] = FNMS(KP951056516, T56, T53);
            Cr[WS(csr, 23)] = FMA(KP951056516, T56, T53);
            T5r = SUB(T5p, T5q);
            T5s = SUB(T57, T58);
            Ci[WS(csi, 7)] = FMA(KP951056516, T5s, T5r);
            Ci[WS(csi, 23)] = FNMS(KP951056516, T5s, T5r);
          }
        }
      }
      {
        E T24, T25, T33, T3P, T3F, T3T, T2s, T4A, T3o, T3S, T36, T3Q,
         T49, T4x, T4q;
        E T17, T3V, T3J, T4k, T4w, T4p, T1i, T3W, T3M;
        {
          E T3p, T3E, T16, T3H;
          {
            E T1G, T23, T31, T32;
            T1G = ADD(T1q, T1F);
            T23 = ADD(T1N, T22);
            T24 = SUB(T1G, T23);
            T25 = ADD(T1G, T23);
            T31 = FNMS(KP500000000, T2f, T28);
            T32 = SUB(T15, T12);
            T33 = FNMS(KP910592997, T32, T31);
            T3P = FMA(KP910592997, T32, T31);
          }
          T3p = FNMS(KP500000000, T22, T1N);
          T3E = SUB(T3w, T3D);
          T3F = FNMS(KP910592997, T3E, T3p);
          T3T = FMA(KP910592997, T3E, T3p);
          {
            E T2g, T2r, T38, T3n;
            T2g = ADD(T28, T2f);
            T2r = ADD(T2j, T2q);
            T2s = ADD(T2g, T2r);
            T4A = SUB(T2g, T2r);
            T38 = FNMS(KP500000000, T1F, T1q);
            T3n = SUB(T3f, T3m);
            T3o = FNMS(KP910592997, T3n, T38);
            T3S = FMA(KP910592997, T3n, T38);
          }
          {
            E T34, T35, T46, T47;
            T34 = FNMS(KP500000000, T2q, T2j);
            T35 = SUB(T1g, T1d);
            T36 = FNMS(KP910592997, T35, T34);
            T3Q = FMA(KP910592997, T35, T34);
            T46 = ADD(T3D, T3w);
            T47 = FNMS(KP500000000, T46, T45);
            T49 = FMA(KP823639103, T48, T47);
            T4x = ADD(T45, T46);
            T4q = FNMS(KP823639103, T48, T47);
          }
          T16 = ADD(T12, T15);
          T3H = FNMS(KP500000000, T16, TZ);
          T17 = ADD(TZ, T16);
          T3V = FNMS(KP823639103, T3I, T3H);
          T3J = FMA(KP823639103, T3I, T3H);
          {
            E T4h, T4i, T1h, T3K;
            T4h = ADD(T3m, T3f);
            T4i = FNMS(KP500000000, T4h, T4g);
            T4k = FMA(KP823639103, T4j, T4i);
            T4w = ADD(T4g, T4h);
            T4p = FNMS(KP823639103, T4j, T4i);
            T1h = ADD(T1d, T1g);
            T3K = FNMS(KP500000000, T1h, T1a);
            T1i = ADD(T1a, T1h);
            T3W = FNMS(KP823639103, T3L, T3K);
            T3M = FMA(KP823639103, T3L, T3K);
          }
        }
        {
          E T4z, T1j, T3R, T3U;
          Ci[WS(csi, 6)] = MUL(KP951056516, SUB(T25, T2s));
          Ci[WS(csi, 24)] = MUL(KP951056516, ADD(T2s, T25));
          T4z = SUB(T4x, T4w);
          Ci[WS(csi, 9)] = FMA(KP951056516, T4A, T4z);
          Ci[WS(csi, 21)] = FNMS(KP951056516, T4A, T4z);
          T1j = SUB(T17, T1i);
          Cr[WS(csr, 21)] = FNMS(KP951056516, T24, T1j);
          Cr[WS(csr, 9)] = FMA(KP951056516, T24, T1j);
          {
            E T4t, T4u, T4v, T4y;
            T4t = ADD(T3V, T3W);
            T4u = ADD(T4p, T4q);
            Cr[WS(csr, 26)] = SUB(T4t, T4u);
            Cr[WS(csr, 4)] = ADD(T4t, T4u);
            T4v = ADD(T17, T1i);
            T4y = ADD(T4w, T4x);
            Cr[WS(csr, 6)] = SUB(T4v, T4y);
            Cr[WS(csr, 24)] = ADD(T4v, T4y);
          }
          T3R = ADD(T3P, T3Q);
          T3U = ADD(T3S, T3T);
          Ci[WS(csi, 4)] = MUL(KP951056516, ADD(T3R, T3U));
          Ci[WS(csi, 26)] = MUL(KP951056516, SUB(T3U, T3R));
          {
            E T4l, T4m, T3N, T3O;
            T4l = SUB(T49, T4k);
            T4m = SUB(T36, T33);
            Ci[WS(csi, 1)] = FMA(KP951056516, T4m, T4l);
            Ci[WS(csi, 29)] = FNMS(KP951056516, T4m, T4l);
            T3N = SUB(T3J, T3M);
            T3O = SUB(T3F, T3o);
            Cr[WS(csr, 29)] = FNMS(KP951056516, T3O, T3N);
            Cr[WS(csr, 1)] = FMA(KP951056516, T3O, T3N);
          }
          {
            E T37, T3G, T4n, T4o;
            T37 = ADD(T33, T36);
            T3G = ADD(T3o, T3F);
            Ci[WS(csi, 14)] = MUL(KP951056516, SUB(T37, T3G));
            Ci[WS(csi, 16)] = NEG(MUL(KP951056516, ADD(T37, T3G)));
            T4n = ADD(T3J, T3M);
            T4o = ADD(T4k, T49);
            Cr[WS(csr, 14)] = SUB(T4n, T4o);
            Cr[WS(csr, 16)] = ADD(T4n, T4o);
          }
          {
            E T3X, T3Y, T4r, T4s;
            T3X = SUB(T3V, T3W);
            T3Y = SUB(T3T, T3S);
            Cr[WS(csr, 11)] = FNMS(KP951056516, T3Y, T3X);
            Cr[WS(csr, 19)] = FMA(KP951056516, T3Y, T3X);
            T4r = SUB(T4p, T4q);
            T4s = SUB(T3Q, T3P);
            Ci[WS(csi, 11)] = FMA(KP951056516, T4s, T4r);
            Ci[WS(csi, 19)] = FNMS(KP951056516, T4s, T4r);
          }
        }
      }
    }
  }
}
