/* Generated by: /Users/sfegan/GitHub/fftw3/genfft/gen_r2cb.native -n 60 -sign 1 -standalone -fma -generic-arith -compact -name dft_codelet_r2cb_60 */

/*
 * This function contains 374 FP additions, 190 FP multiplications,
 * (or, 184 additions, 0 multiplications, 190 fused multiply/add),
 * 92 stack variables, 9 constants, and 120 memory accesses
 */
void dft_codelet_r2cb_60(R * R0, R * R1, R * Cr, R * Ci, stride rs, stride csr, stride csi, INT v, INT ivs, INT ovs)
{
  DK(KP951056516, +0.951056516295153572116439333379382143405698634);
  DK(KP1_732050807, +1.732050807568877293527446341505872366942805254);
  DK(KP559016994, +0.559016994374947424102293417182819058860154590);
  DK(KP250000000, +0.250000000000000000000000000000000000000000000);
  DK(KP1_902113032, +1.902113032590307144232878666758764286811397268);
  DK(KP1_118033988, +1.118033988749894848204586834365638117720309180);
  DK(KP2_000000000, +2.000000000000000000000000000000000000000000000);
  DK(KP500000000, +0.500000000000000000000000000000000000000000000);
  DK(KP618033988, +0.618033988749894848204586834365638117720309180);
  {
    INT i;
    for (i = v; i > 0; i = i - 1, R0 = R0 + ovs, R1 = R1 + ovs, Cr = Cr + ivs, Ci = Ci + ivs, MAKE_VOLATILE_STRIDE(240, rs), MAKE_VOLATILE_STRIDE(240, csr), MAKE_VOLATILE_STRIDE(240, csi)) {
      E T5, T2p, T2N, T15, T2b, T27, T5M, T2J, T3I, T4S, T1L, T5U, T2D,
       T40, T52;
      E TW, T4T, T3L, T20, T2I, TN, T4Q, T3A, T1P, T2F, T1W, T5L, T2G,
       T3x, T4P;
      E TE, T53, T43, T1E, T2C, T1y, T5H, T2y, T3j, T4J, Tk, T2w, T2Q,
       T1o, T2e;
      E Tt, T4K, T3m, T1r, T2x, Te, T4F, T39, T18, T2q, T1f, T5E, T2r,
       T36, T4E;
      {
        E T14, T2o, T1, T4, TZ, T10, T2n, T11;
        {
          E T12, T13, T2, T3;
          T12 = Ci[WS(csi, 12)];
          T13 = Ci[WS(csi, 24)];
          T14 = FMA(KP618033988, T13, T12);
          T2o = FMS(KP618033988, T12, T13);
          T1 = Cr[0];
          T2 = Cr[WS(csr, 12)];
          T3 = Cr[WS(csr, 24)];
          T4 = ADD(T2, T3);
          TZ = FNMS(KP500000000, T4, T1);
          T10 = SUB(T2, T3);
        }
        T5 = FMA(KP2_000000000, T4, T1);
        T2n = FNMS(KP1_118033988, T10, TZ);
        T2p = FNMS(KP1_902113032, T2o, T2n);
        T2N = FMA(KP1_902113032, T2o, T2n);
        T11 = FMA(KP1_118033988, T10, TZ);
        T15 = FMA(KP1_902113032, T14, T11);
        T2b = FNMS(KP1_902113032, T14, T11);
      }
      {
        E T3C, T3D, T3E, T23, T3F, T26, T3G, T3H;
        T3C = Ci[WS(csi, 5)];
        {
          E T21, T22, T24, T25;
          T21 = Ci[WS(csi, 7)];
          T22 = Ci[WS(csi, 17)];
          T3D = SUB(T22, T21);
          T24 = Ci[WS(csi, 19)];
          T25 = Ci[WS(csi, 29)];
          T3E = SUB(T25, T24);
          T23 = ADD(T21, T22);
          T3F = ADD(T3D, T3E);
          T26 = ADD(T24, T25);
        }
        T27 = FMA(KP618033988, T26, T23);
        T5M = ADD(T3F, T3C);
        T2J = FNMS(KP618033988, T23, T26);
        T3G = FNMS(KP250000000, T3F, T3C);
        T3H = SUB(T3E, T3D);
        T3I = FNMS(KP559016994, T3H, T3G);
        T4S = FMA(KP559016994, T3H, T3G);
      }
      {
        E T3U, T3V, T3W, T1H, T3X, T1K, T3Y, T3Z;
        T3U = Ci[WS(csi, 15)];
        {
          E T1F, T1G, T1I, T1J;
          T1F = Ci[WS(csi, 27)];
          T1G = Ci[WS(csi, 3)];
          T3V = ADD(T1F, T1G);
          T1I = Ci[WS(csi, 9)];
          T1J = Ci[WS(csi, 21)];
          T3W = ADD(T1J, T1I);
          T1H = SUB(T1F, T1G);
          T3X = SUB(T3V, T3W);
          T1K = SUB(T1I, T1J);
        }
        T1L = FMA(KP618033988, T1K, T1H);
        T5U = ADD(T3U, T3X);
        T2D = FNMS(KP618033988, T1H, T1K);
        T3Y = FNMS(KP250000000, T3X, T3U);
        T3Z = ADD(T3V, T3W);
        T40 = FMA(KP559016994, T3Z, T3Y);
        T52 = FNMS(KP559016994, T3Z, T3Y);
      }
      {
        E TO, TR, TU, TV, T3K, T3J, T1Y, T1Z;
        TO = Cr[WS(csr, 5)];
        {
          E TP, TQ, TS, TT;
          TP = Cr[WS(csr, 7)];
          TQ = Cr[WS(csr, 17)];
          TR = ADD(TP, TQ);
          TS = Cr[WS(csr, 19)];
          TT = Cr[WS(csr, 29)];
          TU = ADD(TS, TT);
          TV = ADD(TR, TU);
          T3K = SUB(TS, TT);
          T3J = SUB(TP, TQ);
        }
        TW = ADD(TO, TV);
        T4T = FNMS(KP618033988, T3J, T3K);
        T3L = FMA(KP618033988, T3K, T3J);
        T1Y = FNMS(KP250000000, TV, TO);
        T1Z = SUB(TR, TU);
        T20 = FMA(KP559016994, T1Z, T1Y);
        T2I = FNMS(KP559016994, T1Z, T1Y);
      }
      {
        E TF, TI, TL, TM, T3z, T3y, T1N, T1O;
        TF = Cr[WS(csr, 25)];
        {
          E TG, TH, TJ, TK;
          TG = Cr[WS(csr, 13)];
          TH = Cr[WS(csr, 23)];
          TI = ADD(TG, TH);
          TJ = Cr[WS(csr, 1)];
          TK = Cr[WS(csr, 11)];
          TL = ADD(TJ, TK);
          TM = ADD(TI, TL);
          T3z = SUB(TJ, TK);
          T3y = SUB(TG, TH);
        }
        TN = ADD(TF, TM);
        T4Q = FNMS(KP618033988, T3y, T3z);
        T3A = FMA(KP618033988, T3z, T3y);
        T1N = FNMS(KP250000000, TM, TF);
        T1O = SUB(TI, TL);
        T1P = FMA(KP559016994, T1O, T1N);
        T2F = FNMS(KP559016994, T1O, T1N);
      }
      {
        E T3r, T3s, T3t, T1S, T3u, T1V, T3v, T3w;
        T3r = Ci[WS(csi, 25)];
        {
          E T1Q, T1R, T1T, T1U;
          T1Q = Ci[WS(csi, 23)];
          T1R = Ci[WS(csi, 13)];
          T3s = SUB(T1R, T1Q);
          T1T = Ci[WS(csi, 11)];
          T1U = Ci[WS(csi, 1)];
          T3t = SUB(T1U, T1T);
          T1S = ADD(T1Q, T1R);
          T3u = ADD(T3s, T3t);
          T1V = ADD(T1T, T1U);
        }
        T1W = FMA(KP618033988, T1V, T1S);
        T5L = ADD(T3u, T3r);
        T2G = FNMS(KP618033988, T1S, T1V);
        T3v = FNMS(KP250000000, T3u, T3r);
        T3w = SUB(T3t, T3s);
        T3x = FNMS(KP559016994, T3w, T3v);
        T4P = FMA(KP559016994, T3w, T3v);
      }
      {
        E Tw, Tz, TC, TD, T42, T41, T1C, T1D;
        Tw = Cr[WS(csr, 15)];
        {
          E Tx, Ty, TA, TB;
          Tx = Cr[WS(csr, 27)];
          Ty = Cr[WS(csr, 3)];
          Tz = ADD(Tx, Ty);
          TA = Cr[WS(csr, 21)];
          TB = Cr[WS(csr, 9)];
          TC = ADD(TA, TB);
          TD = ADD(Tz, TC);
          T42 = SUB(TA, TB);
          T41 = SUB(Tx, Ty);
        }
        TE = ADD(Tw, TD);
        T53 = FNMS(KP618033988, T41, T42);
        T43 = FMA(KP618033988, T42, T41);
        T1C = FNMS(KP250000000, TD, Tw);
        T1D = SUB(Tz, TC);
        T1E = FMA(KP559016994, T1D, T1C);
        T2C = FNMS(KP559016994, T1D, T1C);
      }
      {
        E T3d, T3e, T3f, T1u, T3g, T1x, T3h, T3i;
        T3d = Ci[WS(csi, 10)];
        {
          E T1s, T1t, T1v, T1w;
          T1s = Ci[WS(csi, 2)];
          T1t = Ci[WS(csi, 22)];
          T3e = SUB(T1s, T1t);
          T1v = Ci[WS(csi, 14)];
          T1w = Ci[WS(csi, 26)];
          T3f = ADD(T1v, T1w);
          T1u = ADD(T1s, T1t);
          T3g = ADD(T3e, T3f);
          T1x = SUB(T1v, T1w);
        }
        T1y = FMA(KP618033988, T1x, T1u);
        T5H = SUB(T3g, T3d);
        T2y = FNMS(KP618033988, T1u, T1x);
        T3h = FMA(KP250000000, T3g, T3d);
        T3i = SUB(T3e, T3f);
        T3j = FNMS(KP559016994, T3i, T3h);
        T4J = FMA(KP559016994, T3i, T3h);
      }
      {
        E T1n, T2v, Tg, Tj, T1i, T1j, T2u, T1k;
        {
          E T1l, T1m, Th, Ti;
          T1l = Ci[WS(csi, 18)];
          T1m = Ci[WS(csi, 6)];
          T1n = FMA(KP618033988, T1m, T1l);
          T2v = FNMS(KP618033988, T1l, T1m);
          Tg = Cr[WS(csr, 30)];
          Th = Cr[WS(csr, 18)];
          Ti = Cr[WS(csr, 6)];
          Tj = ADD(Th, Ti);
          T1i = FNMS(KP500000000, Tj, Tg);
          T1j = SUB(Th, Ti);
        }
        Tk = FMA(KP2_000000000, Tj, Tg);
        T2u = FNMS(KP1_118033988, T1j, T1i);
        T2w = FNMS(KP1_902113032, T2v, T2u);
        T2Q = FMA(KP1_902113032, T2v, T2u);
        T1k = FMA(KP1_118033988, T1j, T1i);
        T1o = FNMS(KP1_902113032, T1n, T1k);
        T2e = FMA(KP1_902113032, T1n, T1k);
      }
      {
        E Tl, To, Tr, Ts, T3l, T3k, T1p, T1q;
        Tl = Cr[WS(csr, 10)];
        {
          E Tm, Tn, Tp, Tq;
          Tm = Cr[WS(csr, 2)];
          Tn = Cr[WS(csr, 22)];
          To = ADD(Tm, Tn);
          Tp = Cr[WS(csr, 14)];
          Tq = Cr[WS(csr, 26)];
          Tr = ADD(Tp, Tq);
          Ts = ADD(To, Tr);
          T3l = SUB(Tp, Tq);
          T3k = SUB(Tm, Tn);
        }
        Tt = ADD(Tl, Ts);
        T4K = FNMS(KP618033988, T3k, T3l);
        T3m = FMA(KP618033988, T3l, T3k);
        T1p = FNMS(KP250000000, Ts, Tl);
        T1q = SUB(To, Tr);
        T1r = FMA(KP559016994, T1q, T1p);
        T2x = FNMS(KP559016994, T1q, T1p);
      }
      {
        E T6, T9, Tc, Td, T38, T37, T16, T17;
        T6 = Cr[WS(csr, 20)];
        {
          E T7, T8, Ta, Tb;
          T7 = Cr[WS(csr, 28)];
          T8 = Cr[WS(csr, 8)];
          T9 = ADD(T7, T8);
          Ta = Cr[WS(csr, 16)];
          Tb = Cr[WS(csr, 4)];
          Tc = ADD(Ta, Tb);
          Td = ADD(T9, Tc);
          T38 = SUB(Ta, Tb);
          T37 = SUB(T7, T8);
        }
        Te = ADD(T6, Td);
        T4F = FNMS(KP618033988, T37, T38);
        T39 = FMA(KP618033988, T38, T37);
        T16 = FNMS(KP250000000, Td, T6);
        T17 = SUB(T9, Tc);
        T18 = FMA(KP559016994, T17, T16);
        T2q = FNMS(KP559016994, T17, T16);
      }
      {
        E T30, T31, T32, T1b, T33, T1e, T34, T35;
        T30 = Ci[WS(csi, 20)];
        {
          E T19, T1a, T1c, T1d;
          T19 = Ci[WS(csi, 28)];
          T1a = Ci[WS(csi, 8)];
          T31 = SUB(T1a, T19);
          T1c = Ci[WS(csi, 4)];
          T1d = Ci[WS(csi, 16)];
          T32 = ADD(T1c, T1d);
          T1b = ADD(T19, T1a);
          T33 = SUB(T31, T32);
          T1e = SUB(T1c, T1d);
        }
        T1f = FNMS(KP618033988, T1e, T1b);
        T5E = ADD(T33, T30);
        T2r = FMA(KP618033988, T1b, T1e);
        T34 = FNMS(KP250000000, T33, T30);
        T35 = ADD(T31, T32);
        T36 = FMA(KP559016994, T35, T34);
        T4E = FNMS(KP559016994, T35, T34);
      }
      {
        E T5N, T5Z, TY, T5K, T5W, T5Y, T5I, T5Q, T5F, T5P, Tv, T5T,
         TX;
        T5N = SUB(T5L, T5M);
        T5Z = SUB(TN, TW);
        TX = ADD(TN, TW);
        TY = ADD(TE, TX);
        T5K = FNMS(KP2_000000000, TE, TX);
        {
          E T5V, T5G, T5D, Tf, Tu;
          T5V = ADD(T5L, T5M);
          T5W = SUB(T5U, T5V);
          T5Y = FMA(KP2_000000000, T5U, T5V);
          T5G = SUB(Tk, Tt);
          T5I = FMA(KP1_732050807, T5H, T5G);
          T5Q = FNMS(KP1_732050807, T5H, T5G);
          T5D = SUB(T5, Te);
          T5F = FMA(KP1_732050807, T5E, T5D);
          T5P = FNMS(KP1_732050807, T5E, T5D);
          Tf = FMA(KP2_000000000, Te, T5);
          Tu = FMA(KP2_000000000, Tt, Tk);
          Tv = ADD(Tf, Tu);
          T5T = SUB(Tf, Tu);
        }
        R0[WS(rs, 15)] = FNMS(KP2_000000000, TY, Tv);
        R1[WS(rs, 22)] = FNMS(KP2_000000000, T5W, T5T);
        R1[WS(rs, 7)] = FMA(KP2_000000000, T5W, T5T);
        R0[0] = FMA(KP2_000000000, TY, Tv);
        {
          E T5J, T5O, T5X, T60;
          T5J = ADD(T5F, T5I);
          T5O = FMA(KP1_732050807, T5N, T5K);
          R0[WS(rs, 25)] = ADD(T5J, T5O);
          R0[WS(rs, 10)] = SUB(T5J, T5O);
          T5X = SUB(T5F, T5I);
          T60 = FNMS(KP1_732050807, T5Z, T5Y);
          R1[WS(rs, 2)] = SUB(T5X, T60);
          R1[WS(rs, 17)] = ADD(T5X, T60);
        }
        {
          E T61, T62, T5R, T5S;
          T61 = SUB(T5P, T5Q);
          T62 = FMA(KP1_732050807, T5Z, T5Y);
          R1[WS(rs, 12)] = SUB(T61, T62);
          R1[WS(rs, 27)] = ADD(T61, T62);
          T5R = ADD(T5P, T5Q);
          T5S = FNMS(KP1_732050807, T5N, T5K);
          R0[WS(rs, 5)] = ADD(T5R, T5S);
          R0[WS(rs, 20)] = SUB(T5R, T5S);
        }
      }
      {
        E T2P, T5p, T5f, T2S, T5q, T5i, T2U, T2X, T5k, T5z, T5u, T5v,
         T5n, T5y;
        {
          E T5e, T2O, T5d, T5h, T2R, T5g;
          T5e = FMA(KP951056516, T4F, T4E);
          T2O = FNMS(KP951056516, T2r, T2q);
          T5d = SUB(T2N, T2O);
          T2P = FMA(KP2_000000000, T2O, T2N);
          T5p = FNMS(KP1_732050807, T5e, T5d);
          T5f = FMA(KP1_732050807, T5e, T5d);
          T5h = FNMS(KP951056516, T4K, T4J);
          T2R = FNMS(KP951056516, T2y, T2x);
          T5g = SUB(T2Q, T2R);
          T2S = FMA(KP2_000000000, T2R, T2Q);
          T5q = FMA(KP1_732050807, T5h, T5g);
          T5i = FNMS(KP1_732050807, T5h, T5g);
        }
        {
          E T2V, T2W, T5l, T5m;
          T2U = FNMS(KP951056516, T2D, T2C);
          T2V = FMA(KP951056516, T2G, T2F);
          T2W = FNMS(KP951056516, T2J, T2I);
          T2X = ADD(T2V, T2W);
          T5k = FNMS(KP2_000000000, T2U, T2X);
          T5z = SUB(T2V, T2W);
          T5u = FMA(KP951056516, T53, T52);
          T5l = FNMS(KP951056516, T4Q, T4P);
          T5m = FNMS(KP951056516, T4T, T4S);
          T5v = ADD(T5l, T5m);
          T5n = SUB(T5l, T5m);
          T5y = FMA(KP2_000000000, T5u, T5v);
        }
        {
          E T2T, T2Y, T5x, T5A;
          T2T = ADD(T2P, T2S);
          T2Y = ADD(T2U, T2X);
          R0[WS(rs, 9)] = FNMS(KP2_000000000, T2Y, T2T);
          R0[WS(rs, 24)] = FMA(KP2_000000000, T2Y, T2T);
          {
            E T5j, T5o, T5B, T5C;
            T5j = ADD(T5f, T5i);
            T5o = FMA(KP1_732050807, T5n, T5k);
            R0[WS(rs, 19)] = ADD(T5j, T5o);
            R0[WS(rs, 4)] = SUB(T5j, T5o);
            T5B = SUB(T5f, T5i);
            T5C = FNMS(KP1_732050807, T5z, T5y);
            R1[WS(rs, 26)] = SUB(T5B, T5C);
            R1[WS(rs, 11)] = ADD(T5B, T5C);
          }
          T5x = SUB(T5p, T5q);
          T5A = FMA(KP1_732050807, T5z, T5y);
          R1[WS(rs, 6)] = SUB(T5x, T5A);
          R1[WS(rs, 21)] = ADD(T5x, T5A);
          {
            E T5t, T5w, T5r, T5s;
            T5t = SUB(T2P, T2S);
            T5w = SUB(T5u, T5v);
            R1[WS(rs, 16)] = FNMS(KP2_000000000, T5w, T5t);
            R1[WS(rs, 1)] = FMA(KP2_000000000, T5w, T5t);
            T5r = ADD(T5p, T5q);
            T5s = FNMS(KP1_732050807, T5n, T5k);
            R0[WS(rs, 29)] = ADD(T5r, T5s);
            R0[WS(rs, 14)] = SUB(T5r, T5s);
          }
        }
      }
      {
        E T1h, T4p, T4f, T1A, T4q, T4i, T1M, T29, T4k, T4z, T4u, T4v,
         T4n, T4y;
        {
          E T4e, T1g, T4d, T4h, T1z, T4g;
          T4e = FNMS(KP951056516, T39, T36);
          T1g = FNMS(KP951056516, T1f, T18);
          T4d = SUB(T15, T1g);
          T1h = FMA(KP2_000000000, T1g, T15);
          T4p = FNMS(KP1_732050807, T4e, T4d);
          T4f = FMA(KP1_732050807, T4e, T4d);
          T4h = FMA(KP951056516, T3m, T3j);
          T1z = FMA(KP951056516, T1y, T1r);
          T4g = SUB(T1o, T1z);
          T1A = FMA(KP2_000000000, T1z, T1o);
          T4q = FMA(KP1_732050807, T4h, T4g);
          T4i = FNMS(KP1_732050807, T4h, T4g);
        }
        {
          E T1X, T28, T4l, T4m;
          T1M = FMA(KP951056516, T1L, T1E);
          T1X = FNMS(KP951056516, T1W, T1P);
          T28 = FMA(KP951056516, T27, T20);
          T29 = ADD(T1X, T28);
          T4k = FNMS(KP2_000000000, T1M, T29);
          T4z = SUB(T1X, T28);
          T4u = FNMS(KP951056516, T43, T40);
          T4l = FMA(KP951056516, T3A, T3x);
          T4m = FMA(KP951056516, T3L, T3I);
          T4v = ADD(T4l, T4m);
          T4n = SUB(T4l, T4m);
          T4y = FMA(KP2_000000000, T4u, T4v);
        }
        {
          E T1B, T2a, T4x, T4A;
          T1B = ADD(T1h, T1A);
          T2a = ADD(T1M, T29);
          R0[WS(rs, 27)] = FNMS(KP2_000000000, T2a, T1B);
          R0[WS(rs, 12)] = FMA(KP2_000000000, T2a, T1B);
          {
            E T4j, T4o, T4B, T4C;
            T4j = ADD(T4f, T4i);
            T4o = FMA(KP1_732050807, T4n, T4k);
            R0[WS(rs, 7)] = ADD(T4j, T4o);
            R0[WS(rs, 22)] = SUB(T4j, T4o);
            T4B = SUB(T4f, T4i);
            T4C = FNMS(KP1_732050807, T4z, T4y);
            R1[WS(rs, 14)] = SUB(T4B, T4C);
            R1[WS(rs, 29)] = ADD(T4B, T4C);
          }
          T4x = SUB(T4p, T4q);
          T4A = FMA(KP1_732050807, T4z, T4y);
          R1[WS(rs, 24)] = SUB(T4x, T4A);
          R1[WS(rs, 9)] = ADD(T4x, T4A);
          {
            E T4t, T4w, T4r, T4s;
            T4t = SUB(T1h, T1A);
            T4w = SUB(T4u, T4v);
            R1[WS(rs, 4)] = FNMS(KP2_000000000, T4w, T4t);
            R1[WS(rs, 19)] = FMA(KP2_000000000, T4w, T4t);
            T4r = ADD(T4p, T4q);
            T4s = FNMS(KP1_732050807, T4n, T4k);
            R0[WS(rs, 17)] = ADD(T4r, T4s);
            R0[WS(rs, 2)] = SUB(T4r, T4s);
          }
        }
      }
      {
        E T2d, T3P, T3b, T2g, T3Q, T3o, T2i, T2l, T3q, T49, T44, T45,
         T3N, T48;
        {
          E T3a, T2c, T2Z, T3n, T2f, T3c;
          T3a = FMA(KP951056516, T39, T36);
          T2c = FMA(KP951056516, T1f, T18);
          T2Z = SUB(T2b, T2c);
          T2d = FMA(KP2_000000000, T2c, T2b);
          T3P = FNMS(KP1_732050807, T3a, T2Z);
          T3b = FMA(KP1_732050807, T3a, T2Z);
          T3n = FNMS(KP951056516, T3m, T3j);
          T2f = FNMS(KP951056516, T1y, T1r);
          T3c = SUB(T2e, T2f);
          T2g = FMA(KP2_000000000, T2f, T2e);
          T3Q = FMA(KP1_732050807, T3n, T3c);
          T3o = FNMS(KP1_732050807, T3n, T3c);
        }
        {
          E T2j, T2k, T3B, T3M;
          T2i = FNMS(KP951056516, T1L, T1E);
          T2j = FMA(KP951056516, T1W, T1P);
          T2k = FNMS(KP951056516, T27, T20);
          T2l = ADD(T2j, T2k);
          T3q = FNMS(KP2_000000000, T2i, T2l);
          T49 = SUB(T2j, T2k);
          T44 = FMA(KP951056516, T43, T40);
          T3B = FNMS(KP951056516, T3A, T3x);
          T3M = FNMS(KP951056516, T3L, T3I);
          T45 = ADD(T3B, T3M);
          T3N = SUB(T3B, T3M);
          T48 = FMA(KP2_000000000, T44, T45);
        }
        {
          E T2h, T2m, T47, T4a;
          T2h = ADD(T2d, T2g);
          T2m = ADD(T2i, T2l);
          R0[WS(rs, 3)] = FNMS(KP2_000000000, T2m, T2h);
          R0[WS(rs, 18)] = FMA(KP2_000000000, T2m, T2h);
          {
            E T3p, T3O, T4b, T4c;
            T3p = ADD(T3b, T3o);
            T3O = FMA(KP1_732050807, T3N, T3q);
            R0[WS(rs, 13)] = ADD(T3p, T3O);
            R0[WS(rs, 28)] = SUB(T3p, T3O);
            T4b = SUB(T3b, T3o);
            T4c = FNMS(KP1_732050807, T49, T48);
            R1[WS(rs, 20)] = SUB(T4b, T4c);
            R1[WS(rs, 5)] = ADD(T4b, T4c);
          }
          T47 = SUB(T3P, T3Q);
          T4a = FMA(KP1_732050807, T49, T48);
          R1[0] = SUB(T47, T4a);
          R1[WS(rs, 15)] = ADD(T47, T4a);
          {
            E T3T, T46, T3R, T3S;
            T3T = SUB(T2d, T2g);
            T46 = SUB(T44, T45);
            R1[WS(rs, 10)] = FNMS(KP2_000000000, T46, T3T);
            R1[WS(rs, 25)] = FMA(KP2_000000000, T46, T3T);
            T3R = ADD(T3P, T3Q);
            T3S = FNMS(KP1_732050807, T3N, T3q);
            R0[WS(rs, 23)] = ADD(T3R, T3S);
            R0[WS(rs, 8)] = SUB(T3R, T3S);
          }
        }
      }
      {
        E T2t, T4X, T4H, T2A, T4Y, T4M, T2E, T2L, T4O, T59, T54, T55,
         T4V, T58;
        {
          E T4G, T2s, T4D, T4L, T2z, T4I;
          T4G = FNMS(KP951056516, T4F, T4E);
          T2s = FMA(KP951056516, T2r, T2q);
          T4D = SUB(T2p, T2s);
          T2t = FMA(KP2_000000000, T2s, T2p);
          T4X = FNMS(KP1_732050807, T4G, T4D);
          T4H = FMA(KP1_732050807, T4G, T4D);
          T4L = FMA(KP951056516, T4K, T4J);
          T2z = FMA(KP951056516, T2y, T2x);
          T4I = SUB(T2w, T2z);
          T2A = FMA(KP2_000000000, T2z, T2w);
          T4Y = FMA(KP1_732050807, T4L, T4I);
          T4M = FNMS(KP1_732050807, T4L, T4I);
        }
        {
          E T2H, T2K, T4R, T4U;
          T2E = FMA(KP951056516, T2D, T2C);
          T2H = FNMS(KP951056516, T2G, T2F);
          T2K = FMA(KP951056516, T2J, T2I);
          T2L = ADD(T2H, T2K);
          T4O = FNMS(KP2_000000000, T2E, T2L);
          T59 = SUB(T2H, T2K);
          T54 = FNMS(KP951056516, T53, T52);
          T4R = FMA(KP951056516, T4Q, T4P);
          T4U = FMA(KP951056516, T4T, T4S);
          T55 = ADD(T4R, T4U);
          T4V = SUB(T4R, T4U);
          T58 = FMA(KP2_000000000, T54, T55);
        }
        {
          E T2B, T2M, T57, T5a;
          T2B = ADD(T2t, T2A);
          T2M = ADD(T2E, T2L);
          R0[WS(rs, 21)] = FNMS(KP2_000000000, T2M, T2B);
          R0[WS(rs, 6)] = FMA(KP2_000000000, T2M, T2B);
          {
            E T4N, T4W, T5b, T5c;
            T4N = ADD(T4H, T4M);
            T4W = FMA(KP1_732050807, T4V, T4O);
            R0[WS(rs, 1)] = ADD(T4N, T4W);
            R0[WS(rs, 16)] = SUB(T4N, T4W);
            T5b = SUB(T4H, T4M);
            T5c = FNMS(KP1_732050807, T59, T58);
            R1[WS(rs, 8)] = SUB(T5b, T5c);
            R1[WS(rs, 23)] = ADD(T5b, T5c);
          }
          T57 = SUB(T4X, T4Y);
          T5a = FMA(KP1_732050807, T59, T58);
          R1[WS(rs, 18)] = SUB(T57, T5a);
          R1[WS(rs, 3)] = ADD(T57, T5a);
          {
            E T51, T56, T4Z, T50;
            T51 = SUB(T2t, T2A);
            T56 = SUB(T54, T55);
            R1[WS(rs, 28)] = FNMS(KP2_000000000, T56, T51);
            R1[WS(rs, 13)] = FMA(KP2_000000000, T56, T51);
            T4Z = ADD(T4X, T4Y);
            T50 = FNMS(KP1_732050807, T4V, T4O);
            R0[WS(rs, 11)] = ADD(T4Z, T50);
            R0[WS(rs, 26)] = SUB(T4Z, T50);
          }
        }
      }
    }
  }
}
